FROM node:20-slim

WORKDIR /app

# Install system dependencies for Playwright
RUN apt-get update && apt-get install -y \
    bash \
    curl \
    git \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

COPY frontend/package*.json ./

# Install npm dependencies
RUN npm install

COPY frontend . .

# Install Playwright browsers
RUN npx playwright install chromium

ENV DOCKER_INTERNAL=true

ENTRYPOINT ["npm", "run", "test:e2e"]




